version: '3'
services:
  postgres:
    image: postgres
    container_name: db
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    volumes:
      - ../../postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    driver: "bridge"
